#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.11

testStep: &testStep
  step:
    name: Test
    caches:
      - pip
    script:
      - apt-get update && apt-get -y install binutils libproj-dev gdal-bin default-mysql-client
      - pip install --upgrade pip pipenv
      - pipenv install --dev --system
      - mysql -h 127.0.0.1 -u root -proot_password -e "GRANT ALL PRIVILEGES ON *.* TO 'bcfg_sa'@'%' WITH GRANT OPTION; FLUSH PRIVILEGES;"
      - pytest -n auto
    services:
      - mysql
      - redis
lintStep: &lintStep
  step:
    name: Lint code
    script:
      - pip install ruff
      - ruff check .
    caches:
      - pip

securityStep: &securityStep
  step:
    name: Security scan
    caches:
      - node
      - pip
    script:
      - pip install --upgrade pip pipenv
      - pipenv install
      - curl --compressed https://static.snyk.io/cli/latest/snyk-linux -o snyk
      - chmod +x ./snyk
      - ./snyk auth $SNYK_TOKEN
      - ./snyk test

pipelines:
  default:
    - parallel:
        - <<: *testStep
        - <<: *lintStep
        - <<: *securityStep

definitions:
  services:
    mysql: 
      image: mysql:8.0
      variables: 
        MYSQL_DATABASE: 'db'
        MYSQL_ROOT_PASSWORD: 'root_password' 
        MYSQL_USER: 'bcfg_sa'
        MYSQL_PASSWORD: 'root_password'
    redis:
      image: redis
