services:
  web:
    build:
      dockerfile: Dockerfile
      target: development
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - .:/workspace:cached
      - .:/app
    command: /bin/sh -c "while sleep 1000; do :; done" 


  db:
    image: mysql:8.0
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "UTC"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  
  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    command: celery -A config worker -l info
    depends_on:
      - redis
      - db
      - web
  
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    command: celery -A config beat -l info
    depends_on:
      - redis
      - db


volumes:
  mysql_data:
