services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    environment:
      - TZ=UTC
    ports:
      - "8000:8000"
    # command: "gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers=3"
  
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=UTC
    command: celery -A config worker -l info
    depends_on:
      - web
  
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=UTC
    command: celery -A config beat -l info
    depends_on:
      - web
