services:
  web:
    build:
      dockerfile: Dockerfile
      target: development
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - .:/workspace:cached
      - .:/app
    command: /bin/sh -c "while sleep 1000; do :; done" 


  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: "UTC"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  
  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    command: celery -A config worker -l info
    depends_on:
      - redis
      - db
      - web
  
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
      - db


volumes:
  postgres_data:
