# Generated by Django 5.1.7 on 2025-03-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0012_individualpipelinerecord_instruction_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="individualpipelinerecord",
            name="skipped",
            field=models.BooleanField(default=False),
        ),
    ]
