# Generated by Django 5.2 on 2025-04-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0014_prompt_type_user_message_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="individualpipelinerecord",
            name="failed",
        ),
        migrations.RemoveField(
            model_name="individualpipelinerecord",
            name="ingested",
        ),
        migrations.RemoveField(
            model_name="individualpipelinerecord",
            name="moderated",
        ),
        migrations.RemoveField(
            model_name="individualpipelinerecord",
            name="processed",
        ),
        migrations.RemoveField(
            model_name="individualpipelinerecord",
            name="sent",
        ),
        migrations.RemoveField(
            model_name="individualpipelinerecord",
            name="shortened",
        ),
        migrations.RemoveField(
            model_name="individualpipelinerecord",
            name="skipped",
        ),
        migrations.AddField(
            model_name="individualpipelinerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("INGEST_PASSED", "Ingest Passed"),
                    ("MODERATION_BLOCKED", "Moderation Blocked"),
                    ("MODERATION_PASSED", "Moderation Passed"),
                    ("PROCESS_PASSED", "Process Passed"),
                    ("PROCESS_SKIPPED", "Process Skipped"),
                    ("VALIDATE_PASSED", "Validate Passed"),
                    ("SEND_PASSED", "Send Passed"),
                    ("FAILED", "Failed"),
                ],
                default="INGEST_PASSED",
                max_length=50,
            ),
        ),
    ]
