# Generated by Django 5.1.7 on 2025-04-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0014_prompt_type_user_message_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="individualpipelinerecord",
            name="failed",
        ),
        migrations.RemoveField(
            model_name="individualpipelinerecord",
            name="ingested",
        ),
        migrations.RemoveField(
            model_name="individualpipelinerecord",
            name="moderated",
        ),
        migrations.RemoveField(
            model_name="individualpipelinerecord",
            name="processed",
        ),
        migrations.RemoveField(
            model_name="individualpipelinerecord",
            name="sent",
        ),
        migrations.RemoveField(
            model_name="individualpipelinerecord",
            name="shortened",
        ),
        migrations.RemoveField(
            model_name="individualpipelinerecord",
            name="skipped",
        ),
        migrations.AddField(
            model_name="individualpipelinerecord",
            name="stages",
            field=models.JSONField(default=list),
        ),
    ]
