# Generated by Django 5.1.8 on 2025-04-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0016_auto_20250408_1238"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chattranscript",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="control",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Control Prompts",
            },
        ),
        migrations.AlterModelOptions(
            name="group",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="groupchattranscript",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="grouppipelinerecord",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="individualpipelinerecord",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="prompt",
            options={
                "ordering": ["week", "type", "-created_at"],
                "verbose_name_plural": "Weekly Prompts",
            },
        ),
        migrations.AlterModelOptions(
            name="strategyprompt",
            options={"ordering": ["is_active", "name"]},
        ),
        migrations.AlterModelOptions(
            name="summary",
            options={"ordering": ["-updated_at"], "verbose_name_plural": "Summaries"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-created_at"]},
        ),
    ]
