# Generated by Django 5.1.8 on 2025-04-09 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0018_groupscheduledtaskassociation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.RemoveField(
            model_name="user",
            name="initial_message",
        ),
        migrations.RemoveField(
            model_name="user",
            name="message_type",
        ),
        migrations.RemoveField(
            model_name="user",
            name="week_number",
        ),
        migrations.CreateModel(
            name="IndividualSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("initial_message", models.TextField()),
                ("week_number", models.IntegerField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial"),
                            ("reminder", "Reminder"),
                            ("check-in", "Check-in"),
                            ("summary", "Summary"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="sessions",
                        to="chat.user",
                    ),
                ),
            ],
        ),
    ]
