# Generated by Django 5.1.8 on 2025-04-09 18:37

import django.db.models.deletion
from django.db import migrations, models

def update_new_fks(apps, schema_editor):
    User = apps.get_model("chat", "User")
    IndividualPipelineRecord = apps.get_model("chat", "IndividualPipelineRecord")

    Group = apps.get_model("chat", "Group")
    GroupPipelineRecord = apps.get_model("chat", "GroupPipelineRecord")

    # Update IndividualPipelineRecord with new user FK
    for record in IndividualPipelineRecord.objects.all():
        try:
            user = User.objects.get(id=record.participant_id)
            record.user = user
            record.save()
        except User.DoesNotExist:
            record.delete()
    
    # Update GroupPipelineRecord with new group FK
    for record in GroupPipelineRecord.objects.all():
        try:
            group = Group.objects.get(id=record.group_id_renamed)
            record.group = group
            record.save()
        except Group.DoesNotExist:
            record.delete()

def reverse_update_new_fks(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0020_alter_individualsession_options_alter_user_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="grouppipelinerecord",
            old_name="group_id",
            new_name="group_id_renamed",
        ),
        migrations.AddField(
            model_name="grouppipelinerecord",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pipeline_records",
                to="chat.group",
            ),
        ),
        migrations.AddField(
            model_name="individualpipelinerecord",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pipeline_records",
                to="chat.user",
            ),
        ),
        migrations.RunPython(
            update_new_fks,
            reverse_update_new_fks,
        ),
    ]
