# Generated by Django 5.1.8 on 2025-04-09 21:00

import django.db.models.deletion
from django.db import migrations, models


def update_new_fks(apps, schema_editor):
    IndividualSession = apps.get_model("chat", "IndividualSession")
    ChatTranscript = apps.get_model("chat", "ChatTranscript")

    # Update IndividualPipelineRecord with new user FK
    for record in ChatTranscript.objects.all():
        session = IndividualSession.objects.filter(user=record.user).order_by("-created_at").first()
        if session:
            record.session = session
            record.save()
        else:
            record.delete()

def reverse_update_new_fks(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0022_remove_grouppipelinerecord_group_id_renamed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chattranscript",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="transcripts",
                to="chat.individualsession",
            ),
        ),
        migrations.RunPython(
            update_new_fks,
            reverse_update_new_fks,
        ),
    ]
