# Generated by Django 5.1.8 on 2025-04-10 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0024_remove_chattranscript_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="individualsession",
            name="initial_message",
        ),
    ]
