# Generated by Django 5.1.8 on 2025-04-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0026_alter_chattranscript_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chattranscript",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("not_evaluated", "Notevaluated"),
                    ("flagged", "Flagged"),
                    ("not_flagged", "Notflagged"),
                ],
                default="not_evaluated",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="historicalchattranscript",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("not_evaluated", "Notevaluated"),
                    ("flagged", "Flagged"),
                    ("not_flagged", "Notflagged"),
                ],
                default="not_evaluated",
                max_length=15,
            ),
        ),
    ]
