# Generated by Django 5.1.8 on 2025-04-14 16:52

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0028_auto_20250414_1618"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HistoricalChatTranscript",
            new_name="HistoricalIndividualChatTranscript",
        ),
        migrations.RenameModel(
            old_name="ChatTranscript",
            new_name="IndividualChatTranscript",
        ),
        migrations.AlterModelOptions(
            name="historicalindividualchattranscript",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical individual chat transcript",
                "verbose_name_plural": "historical individual chat transcripts",
            },
        ),
        migrations.RemoveField(
            model_name="group",
            name="initial_message",
        ),
        migrations.RemoveField(
            model_name="group",
            name="users",
        ),
        migrations.RemoveField(
            model_name="groupchattranscript",
            name="group",
        ),
        migrations.RemoveField(
            model_name="grouppipelinerecord",
            name="failed",
        ),
        migrations.RemoveField(
            model_name="grouppipelinerecord",
            name="ingested",
        ),
        migrations.RemoveField(
            model_name="grouppipelinerecord",
            name="processed",
        ),
        migrations.RemoveField(
            model_name="grouppipelinerecord",
            name="sent",
        ),
        migrations.RemoveField(
            model_name="historicalgroup",
            name="initial_message",
        ),
        migrations.RemoveField(
            model_name="historicalgroupchattranscript",
            name="group",
        ),
        migrations.RemoveField(
            model_name="historicalgrouppipelinerecord",
            name="failed",
        ),
        migrations.RemoveField(
            model_name="historicalgrouppipelinerecord",
            name="ingested",
        ),
        migrations.RemoveField(
            model_name="historicalgrouppipelinerecord",
            name="processed",
        ),
        migrations.RemoveField(
            model_name="historicalgrouppipelinerecord",
            name="sent",
        ),
        migrations.AddField(
            model_name="groupchattranscript",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("not_evaluated", "Notevaluated"),
                    ("flagged", "Flagged"),
                    ("not_flagged", "Notflagged"),
                ],
                default="not_evaluated",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="grouppipelinerecord",
            name="instruction_prompt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grouppipelinerecord",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grouppipelinerecord",
            name="response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grouppipelinerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("INGEST_PASSED", "Ingest Passed"),
                    ("MODERATION_BLOCKED", "Moderation Blocked"),
                    ("MODERATION_PASSED", "Moderation Passed"),
                    ("FAILED", "Failed"),
                ],
                default="INGEST_PASSED",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="grouppipelinerecord",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_pipeline_records",
                to="chat.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="grouppipelinerecord",
            name="validated_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalgroupchattranscript",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("not_evaluated", "Notevaluated"),
                    ("flagged", "Flagged"),
                    ("not_flagged", "Notflagged"),
                ],
                default="not_evaluated",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="historicalgrouppipelinerecord",
            name="instruction_prompt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalgrouppipelinerecord",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalgrouppipelinerecord",
            name="response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalgrouppipelinerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("INGEST_PASSED", "Ingest Passed"),
                    ("MODERATION_BLOCKED", "Moderation Blocked"),
                    ("MODERATION_PASSED", "Moderation Passed"),
                    ("FAILED", "Failed"),
                ],
                default="INGEST_PASSED",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="historicalgrouppipelinerecord",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="chat.user",
            ),
        ),
        migrations.AddField(
            model_name="historicalgrouppipelinerecord",
            name="validated_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalprompt",
            name="is_for_group",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="group",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="chat.group",
            ),
        ),
        migrations.AddField(
            model_name="prompt",
            name="is_for_group",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="users",
                to="chat.group",
            ),
        ),
        migrations.AlterField(
            model_name="grouppipelinerecord",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_pipeline_records",
                to="chat.group",
            ),
        ),
        migrations.AlterField(
            model_name="individualpipelinerecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="individual_pipeline_records",
                to="chat.user",
            ),
        ),
        migrations.CreateModel(
            name="GroupSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("week_number", models.IntegerField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial"),
                            ("reminder", "Reminder"),
                            ("check-in", "Check-in"),
                            ("summary", "Summary"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="sessions",
                        to="chat.group",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="groupchattranscript",
            name="session",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="transcripts",
                to="chat.groupsession",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalgroupchattranscript",
            name="session",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="chat.groupsession",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalGroupSession",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("week_number", models.IntegerField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial"),
                            ("reminder", "Reminder"),
                            ("check-in", "Check-in"),
                            ("summary", "Summary"),
                        ],
                        max_length=20,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="chat.group",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical group session",
                "verbose_name_plural": "historical group sessions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
