# Generated by Django 5.1.8 on 2025-04-14 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "chat",
            "0029_rename_historicalchattranscript_historicalindividualchattranscript_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="week_number",
        ),
        migrations.RemoveField(
            model_name="historicalgroup",
            name="week_number",
        ),
    ]
