# Generated by Django 5.1.8 on 2025-04-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0030_remove_group_week_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupchattranscript",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("not_evaluated", "Not Evaluated"),
                    ("flagged", "Flagged"),
                    ("not_flagged", "Not Flagged"),
                ],
                default="not_evaluated",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="historicalgroupchattranscript",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("not_evaluated", "Not Evaluated"),
                    ("flagged", "Flagged"),
                    ("not_flagged", "Not Flagged"),
                ],
                default="not_evaluated",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="historicalindividualchattranscript",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("not_evaluated", "Not Evaluated"),
                    ("flagged", "Flagged"),
                    ("not_flagged", "Not Flagged"),
                ],
                default="not_evaluated",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="individualchattranscript",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("not_evaluated", "Not Evaluated"),
                    ("flagged", "Flagged"),
                    ("not_flagged", "Not Flagged"),
                ],
                default="not_evaluated",
                max_length=15,
            ),
        ),
    ]
