# Generated by Django 5.1.8 on 2025-04-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0031_alter_groupchattranscript_moderation_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupsession",
            name="current_strategy_phase",
            field=models.CharField(
                choices=[
                    ("before_audience", "Before Audience"),
                    ("after_audience", "After Audience"),
                    ("after_reminder", "After Reminder"),
                    ("after_followup", "After Followup"),
                    ("after_summary", "After Summary"),
                ],
                default="before_audience",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicalgroupsession",
            name="current_strategy_phase",
            field=models.CharField(
                choices=[
                    ("before_audience", "Before Audience"),
                    ("after_audience", "After Audience"),
                    ("after_reminder", "After Reminder"),
                    ("after_followup", "After Followup"),
                    ("after_summary", "After Summary"),
                ],
                default="before_audience",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="grouppipelinerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("INGEST_PASSED", "Ingest Passed"),
                    ("MODERATION_BLOCKED", "Moderation Blocked"),
                    ("MODERATION_PASSED", "Moderation Passed"),
                    ("PROCESS_SKIPPED", "Process Skipped"),
                    ("FAILED", "Failed"),
                ],
                default="INGEST_PASSED",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="historicalgrouppipelinerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("INGEST_PASSED", "Ingest Passed"),
                    ("MODERATION_BLOCKED", "Moderation Blocked"),
                    ("MODERATION_PASSED", "Moderation Passed"),
                    ("PROCESS_SKIPPED", "Process Skipped"),
                    ("FAILED", "Failed"),
                ],
                default="INGEST_PASSED",
                max_length=50,
            ),
        ),
    ]
