# Generated by Django 5.1.8 on 2025-04-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0033_groupchattranscript_assistant_strategy_phase_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupchattranscript",
            name="assistant_strategy_phase",
            field=models.CharField(
                choices=[
                    ("before_audience", "Before Audience"),
                    ("audience", "Audience"),
                    ("after_audience", "After Audience"),
                    ("reminder", "Reminder"),
                    ("after_reminder", "After Reminder"),
                    ("followup", "Followup"),
                    ("after_followup", "After Followup"),
                    ("summary", "Summary"),
                    ("after_summary", "After Summary"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="groupsession",
            name="current_strategy_phase",
            field=models.CharField(
                choices=[
                    ("before_audience", "Before Audience"),
                    ("audience", "Audience"),
                    ("after_audience", "After Audience"),
                    ("reminder", "Reminder"),
                    ("after_reminder", "After Reminder"),
                    ("followup", "Followup"),
                    ("after_followup", "After Followup"),
                    ("summary", "Summary"),
                    ("after_summary", "After Summary"),
                ],
                default="before_audience",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalgroupchattranscript",
            name="assistant_strategy_phase",
            field=models.CharField(
                choices=[
                    ("before_audience", "Before Audience"),
                    ("audience", "Audience"),
                    ("after_audience", "After Audience"),
                    ("reminder", "Reminder"),
                    ("after_reminder", "After Reminder"),
                    ("followup", "Followup"),
                    ("after_followup", "After Followup"),
                    ("summary", "Summary"),
                    ("after_summary", "After Summary"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalgroupsession",
            name="current_strategy_phase",
            field=models.CharField(
                choices=[
                    ("before_audience", "Before Audience"),
                    ("audience", "Audience"),
                    ("after_audience", "After Audience"),
                    ("reminder", "Reminder"),
                    ("after_reminder", "After Reminder"),
                    ("followup", "Followup"),
                    ("after_followup", "After Followup"),
                    ("summary", "Summary"),
                    ("after_summary", "After Summary"),
                ],
                default="before_audience",
                max_length=20,
            ),
        ),
    ]
