# Generated by Django 5.1.8 on 2025-04-17 13:31

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models

def populate_control_configs(apps, schema_editor):
    ControlConfig = apps.get_model("chat", "ControlConfig")
    Control = apps.get_model("chat", "Control")
    control = Control.objects.order_by("-created_at").first()
    if not control:
        return
    ControlConfig.objects.create(
        key="persona_prompt",
        value=control.persona,
    )
    ControlConfig.objects.create(
        key="system_prompt",
        value=control.system,
    )
    ControlConfig.objects.create(
        key="group_direct_message_persona_prompt",
        value=control.persona,
    )


def reverse_populate_control_configs(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0034_alter_groupchattranscript_assistant_strategy_phase_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlConfig",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.TextField(
                        choices=[
                            ("persona_prompt", "Persona Prompt"),
                            ("system_prompt", "System Prompt"),
                            (
                                "group_direct_message_persona_prompt",
                                "Group Direct Message Persona Prompt",
                            ),
                        ],
                        unique=True,
                    ),
                ),
                ("value", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalControlConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "key",
                    models.TextField(
                        choices=[
                            ("persona_prompt", "Persona Prompt"),
                            ("system_prompt", "System Prompt"),
                            (
                                "group_direct_message_persona_prompt",
                                "Group Direct Message Persona Prompt",
                            ),
                        ],
                        db_index=True,
                    ),
                ),
                ("value", models.TextField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical control config",
                "verbose_name_plural": "historical control configs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name="historicalstrategyprompt",
            name="history_user",
        ),
        migrations.DeleteModel(
            name="StrategyPrompt",
        ),
        migrations.AlterUniqueTogether(
            name="groupsession",
            unique_together={("group", "week_number", "message_type")},
        ),
        migrations.AlterUniqueTogether(
            name="individualsession",
            unique_together={("user", "week_number", "message_type")},
        ),
        migrations.AlterUniqueTogether(
            name="prompt",
            unique_together={("is_for_group", "week", "type")},
        ),
        migrations.DeleteModel(
            name="HistoricalStrategyPrompt",
        ),
        migrations.RunPython(
            populate_control_configs,
            reverse_populate_control_configs,
        ),
    ]
