# Generated by Django 5.1.8 on 2025-04-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0036_delete_control_delete_historicalcontrol"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalindividualpipelinerecord",
            name="is_for_group_direct_messaging",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="individualpipelinerecord",
            name="is_for_group_direct_messaging",
            field=models.BooleanField(default=False),
        ),
    ]
