# Generated by Django 5.1.8 on 2025-04-17 20:01

from django.db import migrations

from django.db import migrations
from django.contrib.auth.models import Group
from admin.models import AuthGroupName

def update_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    standard_user, _ = Group.objects.get_or_create(name=AuthGroupName.StandardUser.value)

    standard_perm_models = [
        "user",
        "group",
        "individualchattranscript",
        "groupchattranscript",
        "individualsession",
        "groupsession",
        "prompt",
        "controlconfig",
        "summary",
        "groupstrategyphaseconfig",
    ]

    # Get all CRUD permissions for allowed models
    standard_perms = Permission.objects.filter(
        codename__regex=rf'^(add|change|delete|view)_({"|".join(standard_perm_models)})$',
        content_type__app_label='chat'
    )

    # Still exclude any historical variants
    standard_perms = standard_perms.exclude(codename__contains='historical')
    standard_user.permissions.add(*standard_perms)    

def reverse_update_group(apps, schema_editor):
    Group.objects.filter(
        name__in=[
            AuthGroupName.StandardUser.value,
        ]
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0038_groupstrategyphaseconfig_and_more"),
    ]

    operations = [
        migrations.RunPython(update_group, reverse_update_group),
    ]
