# Generated by Django 5.2 on 2025-04-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0042_auto_20250418_1234"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalsummary",
            old_name="school",
            new_name="school_name",
        ),
        migrations.RenameField(
            model_name="summary",
            old_name="school",
            new_name="school_name",
        ),
        migrations.RemoveField(
            model_name="historicalsummary",
            name="type",
        ),
        migrations.RemoveField(
            model_name="summary",
            name="type",
        ),
        migrations.AddField(
            model_name="historicalsummary",
            name="selected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalsummary",
            name="week_number",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="summary",
            name="selected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="summary",
            name="week_number",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
