# Generated by Django 5.2 on 2025-04-18 16:38

from zoneinfo import ZoneInfo
from django.db import migrations


def create_summary_celery_task(apps, schema_editor):
    from django_celery_beat.models import PeriodicTask, CrontabSchedule

    crontab, _ = CrontabSchedule.objects.get_or_create(
        minute=0,
        hour=0,
        day_of_week=5,  # Friday (late Thursday/early Friday)
        day_of_month="*",
        month_of_year="*",
        timezone=ZoneInfo('America/Los_Angeles'),
    )
    task, _ = PeriodicTask.objects.get_or_create(
        name="Generate weekly summaries",
        task="chat.services.summaries.generate_weekly_summaries",
        crontab=crontab
    )
    task.save()

def reverse_create_summary_celery_task(apps, schema_editor):
    from django_celery_beat.models import PeriodicTask

    PeriodicTask.objects.filter(
        task="chat.services.summaries.generate_weekly_summaries"
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0043_rename_school_historicalsummary_school_name_and_more"),
    ]

    operations = [
         migrations.RunPython(create_summary_celery_task, reverse_create_summary_celery_task),
    ]
