# Generated by Django 5.2 on 2025-04-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0044_auto_20250418_1638"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controlconfig",
            name="key",
            field=models.TextField(
                choices=[
                    ("persona_prompt", "Persona Prompt"),
                    ("system_prompt", "System Prompt"),
                    (
                        "group_direct_message_persona_prompt",
                        "Group Direct Message Persona Prompt",
                    ),
                    ("school_summary_prompt", "School Summary Prompt"),
                ],
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontrolconfig",
            name="key",
            field=models.TextField(
                choices=[
                    ("persona_prompt", "Persona Prompt"),
                    ("system_prompt", "System Prompt"),
                    (
                        "group_direct_message_persona_prompt",
                        "Group Direct Message Persona Prompt",
                    ),
                    ("school_summary_prompt", "School Summary Prompt"),
                ],
                db_index=True,
            ),
        ),
    ]
