# Generated by Django 5.2 on 2025-04-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):


    dependencies = [
        ("chat", "0047_alter_controlconfig_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupprompt",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("initial", "Initial"),
                    ("reminder", "Reminder"),
                    ("check-in", "Check-in"),
                    ("summary", "Summary"),
                ],
                default="initial",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="groupprompt",
            unique_together={("week", "message_type", "strategy_type")},
        ),
        migrations.AlterModelOptions(
            name="groupprompt",
            options={
                "ordering": ["week", "message_type", "strategy_type"],
                "verbose_name_plural": "Weekly Group Prompts",
            },
        ),
        migrations.AlterField(
            model_name="groupprompt",
            name="message_type",
            field=models.CharField(
                choices=[("initial", "Initial"), ("summary", "Summary")],
                default="initial",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicalgroupprompt",
            name="message_type",
            field=models.CharField(
                choices=[("initial", "Initial"), ("summary", "Summary")],
                default="initial",
                max_length=20,
            ),
        ),
    ]
