# Generated by Django 5.2 on 2025-04-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "chat",
            "0048_groupprompt_message_type_and_more_squashed_0050_alter_groupprompt_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupprompt",
            name="strategy_type",
            field=models.CharField(
                choices=[("followup", "Followup"), ("summary", "Summary")],
                default="followup",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalgroupprompt",
            name="strategy_type",
            field=models.CharField(
                choices=[("followup", "Followup"), ("summary", "Summary")],
                default="followup",
                max_length=20,
            ),
        ),
    ]
