# Generated by Django 5.2 on 2025-05-01 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0051_alter_groupprompt_strategy_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouppipelinerecord",
            name="latency",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name="grouppipelinerecord",
            name="shorten_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalgrouppipelinerecord",
            name="latency",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name="historicalgrouppipelinerecord",
            name="shorten_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalindividualpipelinerecord",
            name="latency",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name="historicalindividualpipelinerecord",
            name="shorten_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="individualpipelinerecord",
            name="latency",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name="individualpipelinerecord",
            name="shorten_count",
            field=models.IntegerField(default=0),
        ),
    ]
