# Generated by Django 5.2 on 2025-05-05 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0051_alter_groupprompt_strategy_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupchattranscript",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_transcripts",
                to="chat.user",
            ),
        ),
        migrations.AlterField(
            model_name="groupchattranscript",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transcripts",
                to="chat.groupsession",
            ),
        ),
        migrations.AlterField(
            model_name="groupsession",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="chat.group",
            ),
        ),
        migrations.AlterField(
            model_name="individualchattranscript",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transcripts",
                to="chat.individualsession",
            ),
        ),
        migrations.AlterField(
            model_name="individualsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="chat.user",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="chat.group",
            ),
        ),
    ]
