# Generated by Django 5.2 on 2025-05-05 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0052_alter_groupchattranscript_sender_and_more"),
        ("chat", "0052_grouppipelinerecord_latency_and_more"),
    ]

    operations = []
