# Generated by Django 5.1.8 on 2025-05-06 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0053_merge_20250505_2347"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouppipelinerecord",
            name="transcript",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pipeline_records",
                to="chat.groupchattranscript",
            ),
        ),
        migrations.AddField(
            model_name="historicalgrouppipelinerecord",
            name="transcript",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="chat.groupchattranscript",
            ),
        ),
        migrations.AddField(
            model_name="historicalindividualpipelinerecord",
            name="transcript",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="chat.individualchattranscript",
            ),
        ),
        migrations.AddField(
            model_name="individualpipelinerecord",
            name="transcript",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pipeline_records",
                to="chat.individualchattranscript",
            ),
        ),
    ]
