# Generated by Django 5.2 on 2025-05-06 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0053_merge_20250505_2347"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupchattranscript",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_transcripts",
                to="chat.user",
            ),
        ),
    ]
