# Generated by Django 5.1.8 on 2025-05-07 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0055_grouppipelinerecord_transcript_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupchattranscript",
            name="chat_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupchattranscript",
            name="instruction_prompt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupchattranscript",
            name="latency",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name="groupchattranscript",
            name="shorten_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="groupchattranscript",
            name="user_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grouppipelinerecord",
            name="chat_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalgroupchattranscript",
            name="chat_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalgroupchattranscript",
            name="instruction_prompt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalgroupchattranscript",
            name="latency",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name="historicalgroupchattranscript",
            name="shorten_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalgroupchattranscript",
            name="user_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalgrouppipelinerecord",
            name="chat_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalindividualchattranscript",
            name="chat_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalindividualchattranscript",
            name="instruction_prompt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalindividualchattranscript",
            name="latency",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name="historicalindividualchattranscript",
            name="shorten_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalindividualchattranscript",
            name="user_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalindividualpipelinerecord",
            name="chat_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="individualchattranscript",
            name="chat_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="individualchattranscript",
            name="instruction_prompt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="individualchattranscript",
            name="latency",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name="individualchattranscript",
            name="shorten_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="individualchattranscript",
            name="user_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="individualpipelinerecord",
            name="chat_history",
            field=models.TextField(blank=True, null=True),
        ),
    ]
