# Generated by Django 5.1.8 on 2025-05-07 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0056_groupchattranscript_chat_history_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupchattranscript",
            name="latency",
            field=models.DurationField(default=datetime.timedelta(0), null=True),
        ),
        migrations.AlterField(
            model_name="groupchattranscript",
            name="shorten_count",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="historicalgroupchattranscript",
            name="latency",
            field=models.DurationField(default=datetime.timedelta(0), null=True),
        ),
        migrations.AlterField(
            model_name="historicalgroupchattranscript",
            name="shorten_count",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="historicalindividualchattranscript",
            name="latency",
            field=models.DurationField(default=datetime.timedelta(0), null=True),
        ),
        migrations.AlterField(
            model_name="historicalindividualchattranscript",
            name="shorten_count",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="individualchattranscript",
            name="latency",
            field=models.DurationField(default=datetime.timedelta(0), null=True),
        ),
        migrations.AlterField(
            model_name="individualchattranscript",
            name="shorten_count",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
