# Generated by Django 5.1.8 on 2025-05-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0057_alter_groupchattranscript_latency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupchattranscript",
            name="content",
            field=models.TextField(
                help_text="The content of the message sent by the Sender"
            ),
        ),
        migrations.AlterField(
            model_name="groupchattranscript",
            name="user_message",
            field=models.TextField(
                blank=True,
                help_text="For chatbot responses, the message from a Participant which triggered the response",
                null=True,
                verbose_name="Message from Participant",
            ),
        ),
        migrations.AlterField(
            model_name="historicalgroupchattranscript",
            name="content",
            field=models.TextField(
                help_text="The content of the message sent by the Sender"
            ),
        ),
        migrations.AlterField(
            model_name="historicalgroupchattranscript",
            name="user_message",
            field=models.TextField(
                blank=True,
                help_text="For chatbot responses, the message from a Participant which triggered the response",
                null=True,
                verbose_name="Message from Participant",
            ),
        ),
        migrations.AlterField(
            model_name="historicalindividualchattranscript",
            name="content",
            field=models.TextField(
                help_text="The content of the message sent by the Sender"
            ),
        ),
        migrations.AlterField(
            model_name="historicalindividualchattranscript",
            name="user_message",
            field=models.TextField(
                blank=True,
                help_text="For chatbot responses, the message from a Participant which triggered the response",
                null=True,
                verbose_name="Message from Participant",
            ),
        ),
        migrations.AlterField(
            model_name="individualchattranscript",
            name="content",
            field=models.TextField(
                help_text="The content of the message sent by the Sender"
            ),
        ),
        migrations.AlterField(
            model_name="individualchattranscript",
            name="user_message",
            field=models.TextField(
                blank=True,
                help_text="For chatbot responses, the message from a Participant which triggered the response",
                null=True,
                verbose_name="Message from Participant",
            ),
        ),
    ]
