# Generated by Django 5.1.9 on 2025-05-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0058_alter_groupchattranscript_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouppipelinerecord",
            name="processed_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalgrouppipelinerecord",
            name="processed_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalindividualpipelinerecord",
            name="processed_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="individualpipelinerecord",
            name="processed_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
