# Generated by Django 5.1.9 on 2025-05-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0059_grouppipelinerecord_processed_message_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grouppipelinerecord",
            name="processed_message",
        ),
        migrations.RemoveField(
            model_name="historicalgrouppipelinerecord",
            name="processed_message",
        ),
        migrations.RemoveField(
            model_name="historicalindividualpipelinerecord",
            name="processed_message",
        ),
        migrations.RemoveField(
            model_name="individualpipelinerecord",
            name="processed_message",
        ),
    ]
