# Generated by Django 5.1.9 on 2025-05-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0061_grouppipelinerecord_processed_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controlconfig",
            name="key",
            field=models.TextField(
                choices=[
                    ("persona_prompt", "Persona Prompt"),
                    ("system_prompt", "System Prompt"),
                    (
                        "group_direct_message_persona_prompt",
                        "Group Direct Message Persona Prompt",
                    ),
                    ("school_summary_prompt", "School Summary Prompt"),
                    (
                        "group_audience_strategy_prompt",
                        "Group Audience Strategy Prompt",
                    ),
                    (
                        "group_reminder_strategy_prompt",
                        "Group Reminder Strategy Prompt",
                    ),
                    ("group_summary_persona_prompt", "Group Summary Persona Prompt"),
                    ("instruction_prompt_template", "Instruction Prompt Template"),
                ],
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontrolconfig",
            name="key",
            field=models.TextField(
                choices=[
                    ("persona_prompt", "Persona Prompt"),
                    ("system_prompt", "System Prompt"),
                    (
                        "group_direct_message_persona_prompt",
                        "Group Direct Message Persona Prompt",
                    ),
                    ("school_summary_prompt", "School Summary Prompt"),
                    (
                        "group_audience_strategy_prompt",
                        "Group Audience Strategy Prompt",
                    ),
                    (
                        "group_reminder_strategy_prompt",
                        "Group Reminder Strategy Prompt",
                    ),
                    ("group_summary_persona_prompt", "Group Summary Persona Prompt"),
                    ("instruction_prompt_template", "Instruction Prompt Template"),
                ],
                db_index=True,
            ),
        ),
    ]
