# Generated by Django 5.1.9 on 2025-05-15 12:19

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0063_alter_controlconfig_key_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SundaySummaryPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("week", models.IntegerField()),
                ("activity", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Sunday Summary Prompts",
                "ordering": ["week"],
            },
        ),
        migrations.AlterField(
            model_name="controlconfig",
            name="key",
            field=models.TextField(
                choices=[
                    ("persona_prompt", "Persona Prompt"),
                    ("system_prompt", "System Prompt"),
                    (
                        "group_direct_message_persona_prompt",
                        "Group Direct Message Persona Prompt",
                    ),
                    (
                        "group_audience_strategy_prompt",
                        "Group Audience Strategy Prompt",
                    ),
                    (
                        "group_reminder_strategy_prompt",
                        "Group Reminder Strategy Prompt",
                    ),
                    ("group_summary_persona_prompt", "Group Summary Persona Prompt"),
                    ("instruction_prompt_template", "Instruction Prompt Template"),
                    (
                        "group_instruction_prompt_template",
                        "Group Instruction Prompt Template",
                    ),
                ],
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontrolconfig",
            name="key",
            field=models.TextField(
                choices=[
                    ("persona_prompt", "Persona Prompt"),
                    ("system_prompt", "System Prompt"),
                    (
                        "group_direct_message_persona_prompt",
                        "Group Direct Message Persona Prompt",
                    ),
                    (
                        "group_audience_strategy_prompt",
                        "Group Audience Strategy Prompt",
                    ),
                    (
                        "group_reminder_strategy_prompt",
                        "Group Reminder Strategy Prompt",
                    ),
                    ("group_summary_persona_prompt", "Group Summary Persona Prompt"),
                    ("instruction_prompt_template", "Instruction Prompt Template"),
                    (
                        "group_instruction_prompt_template",
                        "Group Instruction Prompt Template",
                    ),
                ],
                db_index=True,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalSundaySummaryPrompt",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("week", models.IntegerField()),
                ("activity", models.TextField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical sunday summary prompt",
                "verbose_name_plural": "historical Sunday Summary Prompts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
