# Generated by Django 5.1.9 on 2025-05-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0064_sundaysummaryprompt_alter_controlconfig_key_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sundaysummaryprompt",
            unique_together={("week",)},
        ),
    ]
