# Generated by Django 5.1.9 on 2025-05-20 14:18

from zoneinfo import ZoneInfo
from django.db import migrations


def create_notify_on_missing_summaries_task(apps, schema_editor):
    from django_celery_beat.models import PeriodicTask, CrontabSchedule

    crontab, _ = CrontabSchedule.objects.get_or_create(
        minute=0,
        hour=17,
        day_of_week=5, # Friday
        day_of_month="*",
        month_of_year="*",
        timezone=ZoneInfo('America/Los_Angeles'),
    )
    task, _ = PeriodicTask.objects.get_or_create(
        name="Notify on missing summaries",
        task="chat.services.summaries.notify_on_missing_summaries",
        crontab=crontab
    )
    task.save()

def reverse_create_notify_on_missing_summaries_task(apps, schema_editor):
    from django_celery_beat.models import PeriodicTask

    PeriodicTask.objects.filter(
        task="chat.services.summaries.notify_on_missing_summaries"
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0065_alter_sundaysummaryprompt_unique_together"),
    ]

    operations = [
         migrations.RunPython(create_notify_on_missing_summaries_task, reverse_create_notify_on_missing_summaries_task),
    ]
