# Generated by Django 5.1.9 on 2025-05-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0066_auto_20250520_0718"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="gpt_model",
            field=models.CharField(
                blank=True,
                help_text="The model to use for only test user",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="grouppipelinerecord",
            name="gpt_model",
            field=models.CharField(
                blank=True,
                help_text="The model to use for only test user",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalgroup",
            name="gpt_model",
            field=models.CharField(
                blank=True,
                help_text="The model to use for only test user",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalgrouppipelinerecord",
            name="gpt_model",
            field=models.CharField(
                blank=True,
                help_text="The model to use for only test user",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalindividualpipelinerecord",
            name="gpt_model",
            field=models.CharField(
                blank=True,
                help_text="The model to use for only test user",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="gpt_model",
            field=models.CharField(
                blank=True,
                help_text="The model to use for only test user",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="individualpipelinerecord",
            name="gpt_model",
            field=models.CharField(
                blank=True,
                help_text="The model to use for only test user",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gpt_model",
            field=models.CharField(
                blank=True,
                help_text="The model to use for only test user",
                max_length=100,
                null=True,
            ),
        ),
    ]
