# Generated by Django 5.1.9 on 2025-05-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0067_group_gpt_model_grouppipelinerecord_gpt_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouppipelinerecord",
            name="completion_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grouppipelinerecord",
            name="prompt_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalgrouppipelinerecord",
            name="completion_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalgrouppipelinerecord",
            name="prompt_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalindividualpipelinerecord",
            name="completion_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalindividualpipelinerecord",
            name="prompt_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="individualpipelinerecord",
            name="completion_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="individualpipelinerecord",
            name="prompt_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
