# Generated by Django 5.1.9 on 2025-05-21 14:23

from django.db import migrations

from admin.models import AuthGroupName


def update_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    researcher_user, _ = Group.objects.get_or_create(name=AuthGroupName.ResearcherUser.value)

    researcher_view_perm_models = [
        "user",
        "group",
        "individualchattranscript",
        "groupchattranscript",
        "individualsession",
        "groupsession",
        "individualprompt",
        "groupprompt",
        "controlconfig",
        "summary",
        "groupstrategyphaseconfig",
        "individualpipelinerecord",
        "grouppipelinerecord"
    ]

    # Get all CRUD permissions for allowed models
    researcher_view_perms = Permission.objects.filter(
        codename__regex=rf'^(view)_({"|".join(researcher_view_perm_models)})$',
        content_type__app_label='chat'
    )

    # Still exclude any historical variants
    researcher_view_perms = researcher_view_perms.exclude(codename__contains='historical')
    researcher_user.permissions.add(*researcher_view_perms)   
    
    # Add summary actions
    researcher_summary_perms = Permission.objects.filter(
        codename__regex=rf'^(view|change)_summary$',
        content_type__app_label='chat'
    ).exclude(codename__contains='historical')
    researcher_user.permissions.add(*researcher_summary_perms)   

def reverse_update_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(
        name__in=[
            AuthGroupName.ResearcherUser.value,
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0068_grouppipelinerecord_completion_tokens_and_more"),
    ]

    operations = [migrations.RunPython(update_group, reverse_update_group)]
