# Generated by Django 5.1.9 on 2025-05-24 13:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0069_auto_20250521_0723"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupchattranscript",
            name="hub_initiated",
            field=models.BooleanField(
                default=False,
                help_text="Whether the message was initiated by the hub (e.g. an initial message)",
            ),
        ),
        migrations.AddField(
            model_name="groupchattranscript",
            name="sent_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Estimation of the time at which the message was sent based on information we have",
                verbose_name="Message Sent At",
            ),
        ),
        migrations.AddField(
            model_name="historicalgroupchattranscript",
            name="hub_initiated",
            field=models.BooleanField(
                default=False,
                help_text="Whether the message was initiated by the hub (e.g. an initial message)",
            ),
        ),
        migrations.AddField(
            model_name="historicalgroupchattranscript",
            name="sent_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Estimation of the time at which the message was sent based on information we have",
                verbose_name="Message Sent At",
            ),
        ),
        migrations.AddField(
            model_name="historicalindividualchattranscript",
            name="hub_initiated",
            field=models.BooleanField(
                default=False,
                help_text="Whether the message was initiated by the hub (e.g. an initial message)",
            ),
        ),
        migrations.AddField(
            model_name="historicalindividualchattranscript",
            name="sent_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Estimation of the time at which the message was sent based on information we have",
                verbose_name="Message Sent At",
            ),
        ),
        migrations.AddField(
            model_name="individualchattranscript",
            name="hub_initiated",
            field=models.BooleanField(
                default=False,
                help_text="Whether the message was initiated by the hub (e.g. an initial message)",
            ),
        ),
        migrations.AddField(
            model_name="individualchattranscript",
            name="sent_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Estimation of the time at which the message was sent based on information we have",
                verbose_name="Message Sent At",
            ),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE chat_individualchattranscript
                SET hub_initiated = TRUE
                WHERE id IN (
                    SELECT MIN(id)
                    FROM chat_individualchattranscript
                    WHERE role = 'assistant'
                    GROUP BY session_id
                );
            """,
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="""
                UPDATE chat_groupchattranscript
                SET hub_initiated = TRUE
                WHERE id IN (
                    SELECT MIN(id)
                    FROM chat_groupchattranscript
                    WHERE role = 'assistant'
                    GROUP BY session_id
                );
            """,
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="""
            UPDATE chat_individualchattranscript
            SET sent_at = created_at;
            """,
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="""
            UPDATE chat_groupchattranscript 
            SET sent_at = created_at;
            """,
            reverse_sql="",
        ),
    ]
