# Generated by Django 5.1.11 on 2025-07-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0070_groupchattranscript_hub_initiated_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="groupchattranscript",
            old_name="latency",
            new_name="llm_latency",
        ),
        migrations.RenameField(
            model_name="grouppipelinerecord",
            old_name="latency",
            new_name="llm_latency",
        ),
        migrations.RenameField(
            model_name="historicalgroupchattranscript",
            old_name="latency",
            new_name="llm_latency",
        ),
        migrations.RenameField(
            model_name="historicalgrouppipelinerecord",
            old_name="latency",
            new_name="llm_latency",
        ),
        migrations.RenameField(
            model_name="historicalindividualchattranscript",
            old_name="latency",
            new_name="llm_latency",
        ),
        migrations.RenameField(
            model_name="historicalindividualpipelinerecord",
            old_name="latency",
            new_name="llm_latency",
        ),
        migrations.RenameField(
            model_name="individualchattranscript",
            old_name="latency",
            new_name="llm_latency",
        ),
        migrations.RenameField(
            model_name="individualpipelinerecord",
            old_name="latency",
            new_name="llm_latency",
        ),
    ]
