# Generated by Django 5.1.11 on 2025-07-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0071_rename_latency_groupchattranscript_llm_latency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouppipelinerecord",
            name="request_recieved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grouppipelinerecord",
            name="response_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalgrouppipelinerecord",
            name="request_recieved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalgrouppipelinerecord",
            name="response_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalindividualpipelinerecord",
            name="request_recieved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalindividualpipelinerecord",
            name="response_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="individualpipelinerecord",
            name="request_recieved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="individualpipelinerecord",
            name="response_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
