# Generated by Django 5.1.11 on 2025-07-15 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0072_grouppipelinerecord_request_recieved_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouppipelinerecord",
            name="moderation_latency",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name="historicalgrouppipelinerecord",
            name="moderation_latency",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name="historicalindividualpipelinerecord",
            name="moderation_latency",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name="individualpipelinerecord",
            name="moderation_latency",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
