# Generated by Django 5.1.11 on 2025-07-15 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0073_grouppipelinerecord_moderation_latency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouppipelinerecord",
            name="db_load_latency",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name="historicalgrouppipelinerecord",
            name="db_load_latency",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name="historicalindividualpipelinerecord",
            name="db_load_latency",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name="individualpipelinerecord",
            name="db_load_latency",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
