# Generated by Django 5.1.11 on 2025-07-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0074_grouppipelinerecord_db_load_latency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controlconfig",
            name="key",
            field=models.TextField(
                choices=[
                    ("persona_prompt", "Persona Prompt"),
                    ("system_prompt", "System Prompt"),
                    (
                        "group_direct_message_persona_prompt",
                        "Group Direct Message Persona Prompt",
                    ),
                    (
                        "group_audience_strategy_prompt",
                        "Group Audience Strategy Prompt",
                    ),
                    (
                        "group_reminder_strategy_prompt",
                        "Group Reminder Strategy Prompt",
                    ),
                    ("group_summary_persona_prompt", "Group Summary Persona Prompt"),
                    ("instruction_prompt_template", "Instruction Prompt Template"),
                    (
                        "group_instruction_prompt_template",
                        "Group Instruction Prompt Template",
                    ),
                    ("Transcript Len Cutoff", "Transcript Len Cutoff"),
                ],
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontrolconfig",
            name="key",
            field=models.TextField(
                choices=[
                    ("persona_prompt", "Persona Prompt"),
                    ("system_prompt", "System Prompt"),
                    (
                        "group_direct_message_persona_prompt",
                        "Group Direct Message Persona Prompt",
                    ),
                    (
                        "group_audience_strategy_prompt",
                        "Group Audience Strategy Prompt",
                    ),
                    (
                        "group_reminder_strategy_prompt",
                        "Group Reminder Strategy Prompt",
                    ),
                    ("group_summary_persona_prompt", "Group Summary Persona Prompt"),
                    ("instruction_prompt_template", "Instruction Prompt Template"),
                    (
                        "group_instruction_prompt_template",
                        "Group Instruction Prompt Template",
                    ),
                    ("Transcript Len Cutoff", "Transcript Len Cutoff"),
                ],
                db_index=True,
            ),
        ),
    ]
