# Generated by Django 5.1.13 on 2025-11-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0075_alter_controlconfig_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsummary",
            name="fallback",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="summary",
            name="fallback",
            field=models.BooleanField(default=False),
        ),
    ]
